# Generated by Django 3.0.1 on 2019-12-22 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(verbose_name='date created')),
                ('last_push_on', models.DateTimeField(verbose_name='date of last git push')),
                ('description', models.CharField(max_length=1000)),
                ('star_count', models.IntegerField(default=0)),
            ],
        ),
    ]
