# Generated by Django 3.0.1 on 2019-12-22 22:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('github_repos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='data_retrieved_on',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date of last update'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='repository',
            name='created_on',
            field=models.DateTimeField(verbose_name='date repo was created'),
        ),
    ]
