# Generated by Django 3.0.1 on 2019-12-29 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_repos', '0002_auto_20191222_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
